### ISSUE TITLE
stepping in this function skips too much

### ISSUE THREAD

**Issue by JeffBezanson** [Keno/ASTInterpreter.jl#22]
I can only hit `n` or `s` once in this function before it returns:

```
julia> function f()
        x = 1
        y = 2
       end
f (generic function with 1 method)

julia> @enter f()
Body
├─ none: 2
├─ :(x = 1)
│  ├─ x
│  └─ 1
├─ none: 3
├─ :(y = 2)
│  ├─ y
│  └─ 2
└─ Return
   └─ 2
debug > n
Returning 2

julia> 
```

**Comment by Keno** [comment]
Semantics of the line based stepping are to step to the next call after finishing the current line. I suppose assignments could count too.

**Comment by JeffBezanson** [comment]
I would expect line stepping to step to the next line --- there are line number nodes in there.

**Comment by Keno** [comment]
The first expression on the next line is generally not what you want. It's generally one of the leave nodes, so I had it step through to the call. Assignments would be fine too though.

**Comment by JeffBezanson** [comment]
Ok, stepping to the next assignment might be the answer then. Users will definitely expect some way to run `x=1`, then hit a key, then run `y=2` in this function.
