### ISSUE TITLE
Step through keyword/optional argument wrappers

### ISSUE THREAD

**Issue by Keno** [Keno/ASTInterpreter.jl#25]
I'm not quite sure what to do about this. On the one hand, you probably don't want to see them. On the other hand the optional arguments could have nontrivial code in them. Perhaps step through them in line-stepping mode and do show them when single stepping. Also @JeffBezanson any other such wrappers we should take into account?

**Comment by andreasnoack** [comment]
Continuing https://github.com/Keno/Gallium.jl/issues/85 here: whatever you choose to do with the optional arguments, it would be convenient to have a faster way to get to the function body.
